### ISSUE TITLE
xz_utils can't build on windows with clang

### ISSUE THREAD

**Issue by AndreyMlashkin** [xz-mirror/xz-mirror#3]
Relates to https://github.com/conan-io/conan-center-index/issues/9966

Is there a way to build a lib using clang on windows?

**Comment by simnalamburt** [comment]
I think there should be some way to build xz_utils using *gcc* on windows, but not sure with clang.

Since this repository is just a mirror of xz, why don't you report ask this issue at [XZ Utils forum](https://sourceforge.net/p/lzmautils/discussion/708858) or [XZ mailing lists](https://tukaani.org/xz/lists.html)? People who can answer your question will not be looking at this issue tracker.

###### References
- https://sourceforge.net/p/lzmautils/discussion/708858
- https://tukaani.org/xz/lists.html
